---
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Save packages as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist/

      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        if: startsWith(github.ref, 'refs/tags')
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: >-
          steps.get_tag.outputs.TAG
          && (
            contains(steps.get_tag.outputs.TAG, 'a')
            || contains(steps.get_tag.outputs.TAG, 'b')
            || contains(steps.get_tag.outputs.TAG, 'rc')
          )
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: >-
          steps.get_tag.outputs.TAG
          && !(
            contains(steps.get_tag.outputs.TAG, 'a')
            || contains(steps.get_tag.outputs.TAG, 'b')
            || contains(steps.get_tag.outputs.TAG, 'rc')
          )
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
